### ISSUE TITLE
Kasteren smart home dataset in CSV files

### ISSUE THREAD

**Issue by rebeen** [aitoralmeida/c4a_activity_recognition#1]
please, do you have the original datasets in the CSV file,  if you have it can you give them to me please

**Comment by aitoralmeida** [comment]
Hi,

The original files are in .mat format, you can find them in van Kasteren's page: https://sites.google.com/site/tim0306/codeFramework.zip?attredirects=0

We have converted them to CSV, you can find them in the experiments folder (https://github.com/aitoralmeida/c4a_activity_recognition/tree/master/experiments/kasteren_dataset)

**Comment by rebeen** [comment]
Thank you very much for your replay, actually you only have the houseA datasets in CSV file and also I cannot see the Lable file of the houseA,

**Comment by aitoralmeida** [comment]
You can find the House B and C datasets in the parent folder: https://github.com/aitoralmeida/c4a_activity_recognition/tree/master/experiments

**Comment by rebeen** [comment]
Thank you so much, however, this column format does not work for me I want to have ''Start_time" and "End_time" instead of On and Off
Thank you 
Rebeen

**Comment by aitoralmeida** [comment]
I'm sorry to hear that. Please feel free to preprocess the files and adapt them to the format that you prefer.

**Comment by modaresimr** [comment]
Thank you for your great job
Do you have the original codeFramework.zip because that site is not working anymore

**Comment by aitoralmeida** [comment]
Hi,

I'm afraid that I don't have the original files backed up., but I think that this might be it: http://ailab.wsu.edu/mavhome/datasets/kasterenDataset.zip

I haven't checked it, so maybe there is some missing data. If you crosscheck it against our CSV files, please let me know if it is complete ;-).

**Comment by modaresimr** [comment]
Thank you for your help,
Unfortunately, this zip file only contain 1300 sensor events.

**Comment by aitoralmeida** [comment]
The only other option that I know of is this: https://pypi.org/project/pyadlml/ (I don't know if it is still working)

Otherwise, you can try asking in the ML_News distribution list, I'm sure that someone must have a copy of the original dataset.

**Comment by aitoralmeida** [comment]
Ok, I have just seen that they don't support Kasteren.

**Comment by modaresimr** [comment]
Thanks by the way for introducing that repository;)

**Comment by ispsv** [comment]
Many thanks for the provided experiments, I have one question regarding the reported sensor values - the state is always ON. Does that imply that the sensor is ON only at the times of the sensor readings, and else its state is OFF?
